### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by esprush**
fixed UI loading on localhost:8080/dist instead of localhost:8080

### CODE REVIEW

**Comment by longdogz** [comment]
@esprush , is this a problem only on certain OS's?  I've never had this as a problem when using the script on a Mac.

**Comment by longdogz** [comment]
I checked Mac and our internal build environment, which is Linux.  It still worked fine on both, so I accepted this.  Thanks!

**Comment by esprush** [comment]
longdogz ran into this issue in ubuntu, thanks for this great tool.

**Comment by esprush** [comment]
Thanks for this great tool

Suresh P

**Pull request merged**
