### PR TITLE
Delete user_experiment_index, user_assignment_look_up, user_bucket_index, user_assignment and user_assignment_by_userid

### PR DESCRIPTION
**Pull request by mans4singh**

### CODE REVIEW

**Comment by iizrailevsky** [comment]
👍 :shipit:

**Comment by iizrailevsky** [comment]
👍 for dropping all 3 tables! :shipit:

**Comment by jcwuzoegiver** [comment]
looks good! :shipit:

**Comment by iizrailevsky** [comment]
@mans4singh verified that these are not referenced in prod cassie 👍 :shipit:

**Comment by sudheerkethireddy** [comment]
looks good :shipit:

**Pull request merged**
