### PR TITLE
Adding support for Ubuntu dev environment

### PR DESCRIPTION
**Pull request by vinodtalati**

### CODE REVIEW

**Comment by jwtodd** [comment]
@vinodtalati the included git-diff is a delta between your PR, wasabi:develop and some subtle changes of my own. it looks to work for me, namely:

  % ./bin/wasabi.sh package # gens 2-rpms and 2-debs in the [ws]/target dir

i should've done the changes as a PR against your PR ... but i opted to cut to the chase, see how much work is required and just ran with it creating a diff i hope you and i can work against to get your PR mergable.

let's do this :)

- james

[jwtodd-diff.txt](https://github.com/intuit/wasabi/files/455867/jwtodd-diff.txt)

**Comment by shoeffner** [comment]
We should reflect in the README.md that Ubuntu is supported - currently it states only MacOSX is supported. For my windows branch I basically changed it like this (WIP): https://github.com/intuit/wasabi/blob/feature/windows/README.md#bootstrap-your-environment

**Comment by jwtodd** [comment]
+1 @shoeffner ... good call

**Comment by vinodtalati** [comment]
@jwtodd Changes merged based on your diff. Can you review?

**Comment by vinodtalati** [comment]
Tested on Ubuntu and MAC. Everything works now. Here's the output on Ubuntu (last few lines only):

```
Package version '1.0.20160902232623-SNAPSHOT' includes dashes, converting to underscores {:level=>:warn, :file=>"fpm/package/rpm.rb", :line=>"548", :method=>"version"}
Reading template {:path=>"/usr/local/share/gems/gems/fpm-1.6.2/templates/rpm.erb", :level=>:info, :file=>"fpm/package.rb", :line=>"328", :method=>"template"}
Running rpmbuild {:args=>["rpmbuild", "-bb", "--target", "noarch-unknown-linux", "--define", "buildroot /tmp/package-rpm-build20160906-1-kxdxpz/BUILD", "--define", "_topdir /tmp/package-rpm-build20160906-1-kxdxpz", "--define", "_sourcedir /tmp/package-rpm-build20160906-1-kxdxpz", "--define", "_rpmdir /tmp/package-rpm-build20160906-1-kxdxpz/RPMS", "--define", "_tmppath /tmp", "/tmp/package-rpm-build20160906-1-kxdxpz/SPECS/wasabi-ui-build.spec"], :level=>:info, :file=>"fpm/package/rpm.rb", :line=>"516", :method=>"output"}
Running command {:args=>["rpmbuild", "-bb", "--target", "noarch-unknown-linux", "--define", "buildroot /tmp/package-rpm-build20160906-1-kxdxpz/BUILD", "--define", "_topdir /tmp/package-rpm-build20160906-1-kxdxpz", "--define", "_sourcedir /tmp/package-rpm-build20160906-1-kxdxpz", "--define", "_rpmdir /tmp/package-rpm-build20160906-1-kxdxpz/RPMS", "--define", "_tmppath /tmp", "/tmp/package-rpm-build20160906-1-kxdxpz/SPECS/wasabi-ui-build.spec"], :level=>:debug, :file=>"fpm/util.rb", :line=>"144", :method=>"execmd"}
Process is running {:pid=>11, :level=>:debug, :file=>"fpm/util.rb", :line=>"162", :method=>"execmd"}
Building target platforms: noarch-unknown-linux {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Building for target noarch-unknown-linux {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Executing(%prep): /bin/sh -e /tmp/rpm-tmp.HlcbT2 {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Executing(%build): /bin/sh -e /tmp/rpm-tmp.P08kbO {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Executing(%install): /bin/sh -e /tmp/rpm-tmp.pW9Jtz {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Processing files: wasabi-ui-build-1.0.20160902232623_SNAPSHOT-20160906222030.noarch {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Provides: wasabi-ui-build wasabi-ui-build = 1.0.20160902232623_SNAPSHOT-20160906222030 {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Requires(interp): /bin/sh /bin/sh /bin/sh /bin/sh {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Requires(rpmlib): rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1 {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Requires(pre): /bin/sh {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Requires(post): /bin/sh {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Requires(preun): /bin/sh {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Requires(postun): /bin/sh {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Wrote: /tmp/package-rpm-build20160906-1-kxdxpz/RPMS/noarch/wasabi-ui-build-1.0.20160902232623_SNAPSHOT-20160906222030.noarch.rpm {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Executing(%clean): /bin/sh -e /tmp/rpm-tmp.H5xvo6 {:level=>:info, :file=>"cabin/mixins/pipe.rb", :line=>"47", :method=>"block in pipe"}
Created package {:path=>"wasabi-ui-build-1.0.20160902232623_SNAPSHOT-20160906222030.noarch.rpm", :file=>"clamp/command.rb", :line=>"68", :method=>"run"}
Cleaning up staging path {:path=>"/tmp/package-dir-staging20160906-1-1ryut8y", :level=>:debug, :file=>"fpm/package.rb", :line=>"279", :method=>"cleanup_staging"}
Cleaning up build path {:path=>"/tmp/package-dir-build20160906-1-1il20i7", :level=>:debug, :file=>"fpm/package.rb", :line=>"286", :method=>"cleanup_build"}
Cleaning up build path {:path=>"/tmp/package-rpm-build20160906-1-kxdxpz", :level=>:debug, :file=>"fpm/package.rb", :line=>"286", :method=>"cleanup_build"}
deployable build packages:
./target/wasabi-main-build-1.0.20160902232623_SNAPSHOT-20160906221713.noarch.rpm
./target/wasabi-main-build_1.0.20160902232623-SNAPSHOT-20160906221713_all.deb
./target/wasabi-ui-build-1.0.20160902232623_SNAPSHOT-20160906222030.noarch.rpm
./target/wasabi-ui-build_1.0.20160902232623-SNAPSHOT-20160906222030_all.deb


```

**Comment by jwtodd** [comment]
:ship it:

**Comment by jwtodd** [comment]
Merged :) ... Let's take on the next issue :)

**Pull request merged**
