### PR TITLE
Authentication enabled for user details API

### PR DESCRIPTION
**Pull request by abhishekjain88**
@bargenilesh @iizrailevsky @gittify @longdogz @mooxter @coleenHolden Requesting review.

### CODE REVIEW

**Comment by abhishekjain88** [comment]
Integration tests passed successfully.

**Comment by bargenilesh** [comment]
Changes looks good 👍 , :shipit: provided unit & functional tests pass..

**Comment by gittify** [comment]
:shipit:

**Comment by sudheerkethireddy** [comment]
looks good :shipit:

**Pull request merged**
