### PR TITLE
removed unnecessary module

### PR DESCRIPTION
**Pull request by AndreaSuckro**
Removing the no longer used repository module.

### CODE REVIEW

**Comment by bargenilesh** [comment]
This is good initiative to remove unused modules 👍 ... Along with this 'repository' module, we also should remove 'cassandra' module.

Background: Like 'repository' module 'cassandra' module is also became orphan during datastax-driver-migration project.

**Comment by AndreaSuckro** [comment]
Oh good to know - I removed it aswell :) Thanks for the input!

**Comment by mans4singh** [comment]
Looks good and let's make sure that the functional and unit tests are passing.

**Comment by bargenilesh** [comment]
@AndreaSuckro That was quick 👍 
:shipit: Provided functional tests are passing on wasabi & wasabi-intuit...

**Comment by AndreaSuckro** [comment]
Functional & unit tests verified for wasabi-os, will check later for wasabi-intuit.

**Comment by AndreaSuckro** [comment]
All tests passing.

**Pull request merged**
