### PR TITLE
Move Cassandra cql scripts to resources

### PR DESCRIPTION
**Pull request by jcwuzoegiver**
Move cql scripts under resources so it will be included in the jar so all release jars will include the cql scripts.

### CODE REVIEW

**Comment by jcwuzoegiver** [comment]
@bargenilesh @iizrailevsky pls review

**Comment by abhishekjain88** [comment]
:shipit:

**Comment by abhishekjain88** [comment]
@jcwuzoegiver [cc @bargenilesh @iizrailevsky ] - We missed out on updating the cqlsh docker script with the new location of the mutation scripts. We can either reopen the same PR or fix it as a separate PR. I can do the change if you want.

**Comment by abhishekjain88** [comment]
Added PR here: https://github.com/intuit/wasabi/pull/226

**Comment by gittify** [comment]
as far as it is tested and works :shipit:

**Pull request merged**
