### PR TITLE
added mvn_settings to mvn install

### PR DESCRIPTION
**Pull request by shaikhjamir**
added mvn_settings to man install : This can be used to override the default profile

### CODE REVIEW

**Comment by wasabi-honeybadger** [comment]
@shaikhjamir :shipit:

**Comment by iizrailevsky** [comment]
@shaikhjamir Are you still making changes here?

**Comment by shaikhjamir** [comment]
yes I m working on this, need to resolve the conflicts and do some refactoring

**Comment by shoeffner** [comment]
This seems outdated and not needed anymore. However, feel free to open a new PR or Issue if this is an issue and needs to be fixed.

**Pull request closed without merging**
